### ISSUE TITLE
Preserve query strings when switching creatives

### ISSUE THREAD

**Issue by derekmiranda** [ff0000-ad-tech/wp-creative-server#18]
Mainly for working with Velvet (i.e. keeping addata=blah1234 on switching sizes)

Can try to add this in spare time

**Comment by kennyarehart** [comment]
@derekmiranda you read my mind! I wanted to look into this as well ha. Let me know if i can help in any way

**Comment by derekmiranda** [comment]
@kennyarehart sure thing!
